language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "4"
  - "8"
  - "stable"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
